# ~~~
# This file is part of the dune-xt-functions project:
#   https://github.com/dune-community/dune-xt-functions
# Copyright 2009-2018 dune-xt-functions developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
# Authors:
#   Felix Schindler (2016 - 2017)
#   Rene Milk       (2017 - 2018)
#
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
#          with "runtime exception" (http://www.dune-project.org/license.html)
# ~~~

Module: dune-xt-functions
Version: 18.10
Maintainer: dune-xt-dev@listserv.uni-muenster.de
# dunecontrol only supports the operators "<=", ">=", "=" for version checks, no ranges and no "<", ">", "|", "&", so we duplicate dependencies to get a version range
Depends: dune-testtools (>= 2.5) dune-geometry (>= 2.5) dune-grid (>= 2.5) dune-xt-common (>= 18.10) dune-xt-common (<= 18.10.99) dune-xt-grid (>= 18.10) dune-xt-grid (<= 18.10.99) dune-xt-la (>= 18.10) dune-xt-la (<= 18.10.99) dune-xt-data (>= 18.10) dune-xt-data (<= 18.10.99)
